#!/bin/bash
# Script para crear cuenta Admin en Firebase y Firestore

echo "🔧 Creando cuenta Admin..."
echo ""
echo "Email: uzielisaac28@gmail.com"
echo "Rol: admin"
echo ""
echo "PASOS MANUALES:"
echo ""
echo "1. Ve a Firebase Console:"
echo "   https://console.firebase.google.com/project/integradorhub/authentication/users"
echo ""
echo "2. Click en 'Add User'"
echo ""
echo "3. Ingresa:"
echo "   Email: uzielisaac28@gmail.com"
echo "   Password: [tu contraseña segura]"
echo ""
echo "4. Copia el UID generado"
echo ""
echo "5. Ve a Firestore:"
echo "   https://console.firebase.google.com/project/integradorhub/firestore"
echo ""
echo "6. En la colección 'users', crea un documento con:"
echo "   Document ID: [el UID copiado]"
echo "   Campos:"
echo "     - email: uzielisaac28@gmail.com"
echo "     - nombre: Admin"
echo "     - rol: admin"
echo "     - is_first_login: false"
echo "     - created_at: [timestamp actual]"
echo ""
echo "✅ Listo! Ahora puedes iniciar sesión como admin"
